ARG PYTHON_VERSION=3.12

FROM --platform=linux/amd64 public.ecr.aws/lambda/python:${PYTHON_VERSION}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /tmp
ARG API_VERSION=0.1.1
RUN dnf install -y git
RUN uv pip install git+https://github.com/developmentseed/stac-fastapi-collection-discovery@v0.2.1[lambda] --compile-bytecode --no-binary pydantic --target /asset

CMD ["echo", "hello world"]

