ARG PYTHON_VERSION=3.11
ARG API_VERSION=0.1.0

FROM public.ecr.aws/lambda/python:${PYTHON_VERSION}

WORKDIR /tmp
RUN python -m pip install pip -U

RUN python -m pip install --no-cache-dir federated-collection-search[aws_lambda]==${API_VERSION} -t /asset --no-binary pydantic

CMD ["echo", "hello world"]

